# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Posts
email: thantzinoo.dev@gmail.com
description: >
  Thoughts & Notes
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mgthantzin.github.io" # the base hostname & protocol for your site
paginate:	7 # The number of posts to show per page on your homepage

name: 'Thant Zin Oo'
bio: >
  A social liberalist
author_image: "/assets/images/author.jpg"
twitter_username: mgthantzin
github_username:  mgthantzin

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
